source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'GoRecord' do
    pod 'Alamofire', '~> 4.3'
    pod 'ReactiveCocoa', '~> 5.0.0'
    pod 'ReactiveSwift', '~> 1.0.0'
    pod 'AlamofireImage', '~> 3.1'
end